export const NAV_PUSH = 'NAV_PUSH';
export const NAV_POP = 'NAV_POP';
export const NAV_JUMP_TO_KEY = 'NAV_JUMP_TO_KEY';
export const NAV_JUMP_TO_INDEX = 'NAV_JUMP_TO_INDEX';
export const NAV_RESET = 'NAV_RESET';

//app actions
export const CHANGE_TAB = 'CHANGE_TAB';
export const FETCH_CHAPTERS_REQUESTED = 'FETCH_CHAPTERS_REQUESTED';
export const FETCH_CHAPTERS_SUCCEEDED = 'FETCH_CHAPTERS_SUCCEEDED';
export const FETCH_CHAPTERS_FAILED = 'FETCH_CHAPTERS_FAILED';

